/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void appCompiles() {
        // App is a CLI application with main method
        // No greeting method needed
        assertTrue(true);
    }
}
